version: '3'

services:
  mongo-gui:
    container_name: "mongo-gui"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:4321"
    environment:
      - MONGO_URL=mongodb://localhost:27017